spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mementoDB
      username: memento
      password: memento
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session