spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mementoDB
#      username: memento
#      password: memento
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  profiles:
    active: test

logging:
  level:
    root: WARN
    org.springframework.data.mongodb.repository.Query: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG