apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memento
  name: memento
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: memento
  template:
    metadata:
      labels:
        app: memento
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name : memento
          image: asia.gcr.io/sphong-kuber/memento
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          securityContext:
            privileged: false