apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
#  annotations:
#    kubernetes.io/ingress.global-static-ip-name: "memento-static-ip"
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
              serviceName: memento
              servicePort: 8080